### ISSUE TITLE
cannot open file error

### ISSUE THREAD

**Issue by LittleTale** [Shadowth117/PSO2-Salon-Tool#1]
error: file version unknown. if this is a proper salon file, please report this!

Thanks a lot in advance.

great work on the app btw.
[PSO2 characters.zip](https://github.com/Shadowth117/PSO2-Salon-Tool/files/5044420/PSO2.characters.zip)

**Comment by Shadowth117** [comment]
Huh, yeah these are v7 files. They seem almost the same as v6, but with the newer type of accessory sliders. 

I've added support to the source, but I plan to fix a few more things before releasing a binary. Thanks for the info!
