### ISSUE TITLE
V10 Character files

### ISSUE THREAD

**Issue by EternalFlower** [Shadowth117/PSO2-Salon-Tool#5]
Graphics update for JP introduces version 10 of salon files. The file starts with 0A (hex for 10), 956 bytes in sizes.

**Comment by Shadowth117** [comment]
Given the bugginess of the update at hand, I intend to wait for PSO2 global's graphics update before doing this. I'd rather work with it when they themselves decide it's stable enough to show across the world.

**Comment by Shadowth117** [comment]
V10 file support was added with the NGS Tool release.
