### ISSUE TITLE
Add batch convert options

### ISSUE THREAD

**Issue by EternalFlower** [Shadowth117/PSO2-Salon-Tool#6]
Add the ability to select multiple files and convert them in 1 go.

It would be easier to convert a lot of cml files at once.

Also for cml files, you also can pass the option to select the gender/race for all files or keep the original gender/race from cml.

**Comment by Shadowth117** [comment]
I've thought about it some. However, updates will wait until NGS graphics for Global as discussed in the other issue.

**Comment by Shadowth117** [comment]
This was added to the NGS release.
